### PR TITLE
Merging frontend into main

### PR DESCRIPTION
**Pull request by Aryan-Poonacha**
Added separate page for data ingestion step.
Created UI for the search query process.
Added filtering and sorting to searching.

### CODE REVIEW

**Comment by rishabhshah13** [comment]
Good work separating functionality in the code and creating the separate page for data ingestion. Could use some more formatting to better present search results, mainly videos so that they can be rendered in streamlit instead of just the text of the video filename.

**Comment by h0ngxuanli** [comment]
Could add better documentation and comments to better explain each component

**Review by zihanxing — APPROVED** [review]
Solid implementation of the UI

**Review by h0ngxuanli — APPROVED** [review]
Could add better documentation and comments to better explain each component

**Comment by Aryan-Poonacha** [comment]
Added comments and documentation

**Pull request merged**
